export enum DBSuccess {
  DB_SUCCESS = "CONNECTED TO DB",
  DB_WRITE_SUCCESS = "DATA ADDED TO DB",
  DB_READ_SUCCESS = "READING FROM DB",
  DB_SEARCH_SUCCESS = "SEARCHING IN DB",
  DB_ITEM_FOUND = "ITEM FOUND IN DB",
}

export enum UserSuccess {
  USER_CREATED = "NEW USER CREATED SUCCESSFULLY",
  LOGGED_IN = "LOGGED IN SUCCESSFULLY",
  USER_UPDATED = "USER UPDATED SUCCESSFULLY",
  USER_FOUND = "USER EXISTS",
  USER_DELETED = "DELETED THE USER",
  FETCHED_USER = "GOT THE USER",
  FETCHED_USER_LIST = "GOT THE USER LIST",
  ACTIVATED = "ACTIVATED THE USER SUCCESSFULLY",
  DEACTIVATED = "DEACTIVATED THE USER SUCCESSFULLY",
}

export enum AuthSuccess {
  SUCCESS = "LOGGED IN SUCCESSFULLY"
}
